# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "vite-app-extension"
client_id = "09f36b7fd9b591ee630e440485622401"
application_url = "https://dealtime-malaysia-phd-stays.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://dealtime-malaysia-phd-stays.trycloudflare.com/auth/callback",
  "https://dealtime-malaysia-phd-stays.trycloudflare.com/auth/shopify/callback",
  "https://dealtime-malaysia-phd-stays.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "extension-react-tailwind.myshopify.com"
